// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhanwadpeqqfaxsyejww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoYW53YWRwZXFxZmF4c3lland3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODM3ODgsImV4cCI6MjA2ODk1OTc4OH0.rigW3y6dsy-X7_moAfJIQKYOXtHPVY-nAiRzM4HfHNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});